# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 23:10
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('description', models.TextField(default='Just another conference', max_length=255)),
                ('event_date', models.DateTimeField(default=datetime.datetime(2016, 6, 27, 23, 10, 54, 45463))),
                ('deadline', models.DateTimeField(default=datetime.datetime(2016, 6, 17, 23, 10, 54, 45620))),
                ('ts_created', models.DateTimeField(auto_now_add=True)),
                ('ts_updated', models.DateTimeField(auto_now=True)),
                ('listeners', models.ManyToManyField(related_name='conf_listener', to=settings.AUTH_USER_MODEL)),
                ('reporters', models.ManyToManyField(related_name='conf_reporter', to=settings.AUTH_USER_MODEL)),
                ('sponsors', models.ManyToManyField(related_name='conf_sponsor', to='companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Just another report...', max_length=255)),
                ('text', models.TextField(default='Lorem ipsum dolor sit amet...', max_length=1000)),
                ('ts_created', models.DateTimeField(auto_now_add=True)),
                ('ts_updated', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confs.Conference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
