# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 23:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporter',
            name='conference',
        ),
        migrations.RemoveField(
            model_name='reporter',
            name='user',
        ),
        migrations.AlterField(
            model_name='conference',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 17, 23, 11, 55, 276263)),
        ),
        migrations.AlterField(
            model_name='conference',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 27, 23, 11, 55, 276009)),
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
    ]
